# Generated by Django 6.0.2 on 2026-02-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_people_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['email'], name='crudapp_per_email_046b5f_idx'),
        ),
    ]
