# Generated by Django 6.0.2 on 2026-02-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0007_animal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.RemoveField(
            model_name='student1',
            name='department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Flower',
        ),
        migrations.DeleteModel(
            name='People',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='crudapp_per_email_046b5f_idx',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Student3',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-id'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='Not Specified', max_length=100, verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Student Name'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Student1',
        ),
    ]
